apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <html>
    <body style="background-color:lightblue;">
      <h1>Frontend Application (NGINX)</h1>
      <p>This is the Angular UI page</p>
    </body>
    </html>