apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ingress
  region: us-east-1

managedNodeGroups:
- name: ingress
  instanceType: m5.large
  desiredCapacity: 1
  spot: true


  # eksctl delete cluster --config-file clustercreation.yaml

  # eksctl create cluster \
  # --name my-cluster \
  # --region ap-south-1 \
  # --nodegroup-name my-nodes \
  # --node-type t3.medium \
  # --nodes 2